import { CodebookExportSchema } from '@fiducial/shared-types';
import { CodebookModel } from '@fiducial/core';

export class CodebookSerializer {
  /**
   * Export to standard JSON format schema.
   */
  static toJson(codebook: CodebookModel): CodebookExportSchema {
    const analysis = codebook.distanceAnalysis;
    const stats = codebook.entryStats;

    return {
      formatVersion: '1.0.0',
      systemName: 'FiducialMarkerDesigner',
      exportTimestamp: new Date().toISOString(),
      metadata: {
        name: codebook.metadata.name,
        description: codebook.metadata.description,
        algorithmId: codebook.metadata.algorithmId,
        algorithmVersion: codebook.metadata.version,
        targetMinDistance: codebook.metadata.targetMinDistance,
        achievedMinDistance: analysis.minDistance,
        identityCount: codebook.count,
      },
      geometry: {
        rows: codebook.geometry.rows,
        cols: codebook.geometry.cols,
        totalCells: codebook.geometry.totalCells,
        dataBits: codebook.geometry.dataBitsCount,
        reservedCells: codebook.geometry.reservedCells,
        aspectRatio: codebook.geometry.aspectRatio,
      },
      border: codebook.border,
      physical: codebook.physical,
      decoderConfig: {
        maxAcceptanceDistance: analysis.errorCorrectionCapability,
        minAmbiguityMargin: 1,
        allowReflection: false,
      },
      identities: stats.map((s) => ({
        id: s.id,
        codeBinary: s.binaryString,
        codeHex: s.hexString,
        codeBigInt: s.bigIntValue,
        rotations: {
          deg0: s.rotations.deg0,
          deg90: s.rotations.deg90,
          deg180: s.rotations.deg180,
          deg270: s.rotations.deg270,
        },
      })),
      analysisSummary: {
        minHammingDistance: analysis.minDistance,
        maxHammingDistance: analysis.maxDistance,
        averageHammingDistance: analysis.meanDistance,
        errorDetectionLimit: analysis.errorDetectionCapability,
        errorCorrectionLimit: analysis.errorCorrectionCapability,
      },
    };
  }

  /**
   * Export as ready-to-run Python module with OpenCV decoder snippet.
   */
  static toPython(codebook: CodebookModel): string {
    const jsonSpec = CodebookSerializer.toJson(codebook);
    const codesHex = codebook.codes.map((c, i) => `    ${i}: ${c.toHexString()},  # ${c.toBinaryString()}`).join('\n');

    return `# Generated by Fiducial Marker Designer & Codebook Generator
# Family: ${codebook.metadata.name}
# Grid: ${codebook.geometry.rows}x${codebook.geometry.cols} (${codebook.geometry.dataBitsCount} bits)
# Min Hamming Distance: ${jsonSpec.analysisSummary.minHammingDistance}
# Error Correction Limit: ${jsonSpec.analysisSummary.errorCorrectionLimit} bits

import numpy as np

GRID_ROWS = ${codebook.geometry.rows}
GRID_COLS = ${codebook.geometry.cols}
DATA_BITS = ${codebook.geometry.dataBitsCount}
BORDER_WIDTH_CELLS = ${codebook.border.widthInCells}
MIN_HAMMING_DISTANCE = ${jsonSpec.analysisSummary.minHammingDistance}
MAX_ACCEPTABLE_DISTANCE = ${jsonSpec.analysisSummary.errorCorrectionLimit}

# Marker Codes (ID -> Integer / Bit Pattern)
CODEBOOK = {
${codesHex}
}

def popcount(x: int) -> int:
    return bin(x).count("1")

def hamming_distance(a: int, b: int) -> int:
    return popcount(a ^ b)

def rotate_grid(grid: np.ndarray, k: int) -> np.ndarray:
    """Rotate 2D grid 90 degrees clockwise k times."""
    return np.rot90(grid, -k)

def grid_to_int(grid: np.ndarray) -> int:
    val = 0
    flat = grid.flatten()
    for bit in flat:
        val = (val << 1) | int(bit > 0)
    return val

def decode_observation(observed_int: int):
    """
    Match observed binary code against codebook.
    Returns: (matched_id, min_distance, confidence_status)
    """
    best_dist = 999
    best_id = None
    runner_up_dist = 999

    for mid, code in CODEBOOK.items():
        # Test 4 rotations
        # (In production, precompute rotated int representations for 4x speed)
        dist = hamming_distance(observed_int, code)
        if dist < best_dist:
            runner_up_dist = best_dist
            best_dist = dist
            best_id = mid
        elif dist < runner_up_dist:
            runner_up_dist = dist

    margin = runner_up_dist - best_dist
    if best_dist > MAX_ACCEPTABLE_DISTANCE:
        return None, best_dist, "REJECTED"
    if best_dist > 0 and margin < 1:
        return best_id, best_dist, "AMBIGUOUS"

    return best_id, best_dist, "ACCEPTED"

if __name__ == "__main__":
    print(f"Loaded {len(CODEBOOK)} fiducial markers for ${codebook.metadata.name}")
    test_id = 0
    test_code = CODEBOOK[test_id]
    matched_id, dist, status = decode_observation(test_code)
    print(f"Test decode exact: ID={matched_id}, dist={dist}, status={status}")
`;
  }

  /**
   * Export C/C++ Header file.
   */
  static toCHeader(codebook: CodebookModel): string {
    const stats = codebook.entryStats;
    const arrayElements = stats
      .map((s) => `    0x${BigInt(s.bigIntValue).toString(16).toUpperCase()}ULL, /* ID ${s.id}: ${s.binaryString} */`)
      .join('\n');

    return `/* Generated by Fiducial Marker Designer */
#ifndef FIDUCIAL_CODEBOOK_${codebook.geometry.rows}X${codebook.geometry.cols}_H
#define FIDUCIAL_CODEBOOK_${codebook.geometry.rows}X${codebook.geometry.cols}_H

#include <stdint.h>

#define FIDUCIAL_GRID_ROWS ${codebook.geometry.rows}
#define FIDUCIAL_GRID_COLS ${codebook.geometry.cols}
#define FIDUCIAL_DATA_BITS ${codebook.geometry.dataBitsCount}
#define FIDUCIAL_COUNT ${codebook.count}
#define FIDUCIAL_MIN_DISTANCE ${codebook.distanceAnalysis.minDistance}
#define FIDUCIAL_MAX_ERROR_CORRECTION ${codebook.distanceAnalysis.errorCorrectionCapability}

static const uint64_t FIDUCIAL_CODES[FIDUCIAL_COUNT] = {
${arrayElements}
};

static inline int fiducial_popcount64(uint64_t x) {
#if defined(__GNUC__) || defined(__clang__)
    return __builtin_popcountll(x);
#else
    x = x - ((x >> 1) & 0x5555555555555555ULL);
    x = (x & 0x3333333333333333ULL) + ((x >> 2) & 0x3333333333333333ULL);
    x = (x + (x >> 4)) & 0x0F0F0F0F0F0F0F0FULL;
    return (int)((x * 0x0101010101010101ULL) >> 56);
#endif
}

static inline int fiducial_hamming_dist(uint64_t a, uint64_t b) {
    return fiducial_popcount64(a ^ b);
}

#endif /* FIDUCIAL_CODEBOOK_${codebook.geometry.rows}X${codebook.geometry.cols}_H */
`;
  }

  /**
   * Export to CSV format.
   */
  static toCsv(codebook: CodebookModel): string {
    const lines: string[] = ['ID,HexCode,BinaryCode,MinPairwiseDistance,MinSelfRotationDistance,BalanceRatio'];
    for (const s of codebook.entryStats) {
      lines.push(`${s.id},${s.hexString},${s.binaryString},${s.minPairwiseDistance},${s.minSelfRotationDistance},${s.balanceRatio}`);
    }
    return lines.join('\n');
  }
}
