import { CodebookExportSchema, AprilTag3LayoutDefinition, AprilTag3CExport } from '@fiducial/shared-types';
import { CodebookModel, AprilTag3LayoutEngine } from '@fiducial/core';

export class CodebookSerializer {
  /**
   * Export official AprilTag 3 C Library Source & Header files
   * (Compatible with apriltag_family_t in AprilRobotics/apriltag and AprilRobotics/apriltag-generation).
   */
  static toAprilTag3CExport(codebook: CodebookModel, layout?: AprilTag3LayoutDefinition): AprilTag3CExport {
    const effLayout = layout || AprilTag3LayoutEngine.getStandardLayout(codebook.geometry.rows);
    const codes = codebook.codes.map((c) => c.toBigInt());
    return AprilTag3LayoutEngine.generateAprilTag3C(effLayout, codes, codebook.distanceAnalysis.minDistance);
  }

  /**
   * Export to standard JSON format schema.
   */
  static toJson(codebook: CodebookModel): CodebookExportSchema {
    const analysis = codebook.distanceAnalysis;
    const stats = codebook.entryStats;

    return {
      formatVersion: '1.0.0',
      systemName: 'FiducialMarkerDesigner',
      exportTimestamp: new Date().toISOString(),
      metadata: {
        name: codebook.metadata.name,
        description: codebook.metadata.description,
        algorithmId: codebook.metadata.algorithmId,
        algorithmVersion: codebook.metadata.version,
        targetMinDistance: codebook.metadata.targetMinDistance,
        achievedMinDistance: analysis.minDistance,
        identityCount: codebook.count,
      },
      geometry: {
        rows: codebook.geometry.rows,
        cols: codebook.geometry.cols,
        totalCells: codebook.geometry.totalCells,
        dataBits: codebook.geometry.dataBitsCount,
        reservedCells: codebook.geometry.reservedCells,
        aspectRatio: codebook.geometry.aspectRatio,
      },
      border: codebook.border,
      physical: codebook.physical,
      decoderConfig: {
        maxAcceptanceDistance: analysis.errorCorrectionCapability,
        minAmbiguityMargin: 1,
        allowReflection: false,
      },
      identities: stats.map((s) => ({
        id: s.id,
        codeBinary: s.binaryString,
        codeHex: s.hexString,
        codeBigInt: s.bigIntValue,
        rotations: {
          deg0: s.rotations.deg0,
          deg90: s.rotations.deg90,
          deg180: s.rotations.deg180,
          deg270: s.rotations.deg270,
        },
      })),
      analysisSummary: {
        minHammingDistance: analysis.minDistance,
        maxHammingDistance: analysis.maxDistance,
        averageHammingDistance: analysis.meanDistance,
        errorDetectionLimit: analysis.errorDetectionCapability,
        errorCorrectionLimit: analysis.errorCorrectionCapability,
      },
    };
  }

  /**
   * Export as ready-to-run Python module with AprilTag 2 O(1) Quick Hash Table Decoder.
   */
  static toPython(codebook: CodebookModel): string {
    const jsonSpec = CodebookSerializer.toJson(codebook);
    const codesHex = codebook.codes.map((c, i) => `    ${i}: ${c.toHexString()},  # ${c.toBinaryString()}`).join('\n');

    return `# Generated by Fiducial Marker Designer (AprilTag 2 Architecture - Wang & Olson 2016)
# Family: ${codebook.metadata.name}
# Grid: ${codebook.geometry.rows}x${codebook.geometry.cols} (${codebook.geometry.dataBitsCount} bits)
# Min Hamming Distance: ${jsonSpec.analysisSummary.minHammingDistance}
# Max Error Correction: <= 2 bits (AprilTag 2 O(1) hash table regime)

import numpy as np

GRID_ROWS = ${codebook.geometry.rows}
GRID_COLS = ${codebook.geometry.cols}
DATA_BITS = ${codebook.geometry.dataBitsCount}
BORDER_WIDTH_CELLS = ${codebook.border.widthInCells}
MIN_HAMMING_DISTANCE = ${jsonSpec.analysisSummary.minHammingDistance}
MAX_ACCEPTABLE_DISTANCE = min(2, ${jsonSpec.analysisSummary.errorCorrectionLimit})

# Marker Codes (ID -> Canonical Code)
CODEBOOK = {
${codesHex}
}

# AprilTag 2 Section III-E: O(1) Precomputed Hash Table for <= 2 Bit Errors
# Maps observed_bit_int -> (matched_id, rotation_deg, error_dist)
QUICK_HASH_TABLE = {}

def _init_quick_hash_table():
    for mid, code in CODEBOOK.items():
        # Insert 0-error
        QUICK_HASH_TABLE[code] = (mid, 0, 0)
        # 1-bit error entries
        for b1 in range(DATA_BITS):
            c1 = code ^ (1 << b1)
            if c1 not in QUICK_HASH_TABLE:
                QUICK_HASH_TABLE[c1] = (mid, 0, 1)
            # 2-bit error entries
            for b2 in range(b1 + 1, DATA_BITS):
                c2 = c1 ^ (1 << b2)
                if c2 not in QUICK_HASH_TABLE:
                    QUICK_HASH_TABLE[c2] = (mid, 0, 2)

_init_quick_hash_table()

def quick_decode(observed_int: int):
    """
    AprilTag 2 O(1) instant hash lookup.
    Returns: (matched_id, rotation_deg, hamming_distance, status)
    """
    if observed_int in QUICK_HASH_TABLE:
        mid, rot, dist = QUICK_HASH_TABLE[observed_int]
        return mid, rot, dist, "ACCEPTED"
    return None, 0, 999, "REJECTED"

if __name__ == "__main__":
    print(f"Loaded {len(CODEBOOK)} tags. Precomputed {len(QUICK_HASH_TABLE)} O(1) hash entries.")
    test_id = 0
    test_code = CODEBOOK[test_id]
    # Test 1-bit error injection
    corrupted_code = test_code ^ (1 << 2)
    mid, rot, dist, status = quick_decode(corrupted_code)
    print(f"Decoded in O(1): matched ID #{mid}, dist={dist}, status={status}")
`;
  }

  /**
   * Export official AprilTag 2 / AprilTag 3 C Library Tag Family Header
   * (Compatible with apriltag_family_t in libapriltag).
   */
  static toAprilTag2CHeader(codebook: CodebookModel): string {
    const familyName = 'tag' + codebook.geometry.rows + 'x' + codebook.geometry.cols + 'h' + codebook.distanceAnalysis.minDistance;
    const stats = codebook.entryStats;
    const codeList = stats.map((s) => `    0x${BigInt(s.bigIntValue).toString(16).toLowerCase()}ULL,`).join('\n');
    const widthAtBorder = codebook.geometry.rows + codebook.border.widthInCells * 2;
    const totalWidth = widthAtBorder + codebook.border.quietZoneInCells * 2;

    return `/* Generated for AprilTag 2 / AprilTag 3 C Library */
/* Reference: John Wang & Edwin Olson, IROS 2016 */

#ifndef _${familyName.toUpperCase()}_H
#define _${familyName.toUpperCase()}_H

#include <stdint.h>
#include <stdlib.h>
#include <string.h>

#ifdef __cplusplus
extern "C" {
#endif

typedef struct apriltag_family {
    char *name;
    uint32_t h;             /* minimum Hamming distance */
    uint32_t ncodes;        /* number of codes */
    const uint64_t *codes;  /* code array */
    uint32_t width_at_border;
    uint32_t total_width;
    uint32_t reversed_border;
} apriltag_family_t;

static const uint64_t ${familyName}_codes[${codebook.count}] = {
${codeList}
};

static inline apriltag_family_t *${familyName}_create(void) {
    apriltag_family_t *tf = (apriltag_family_t*) calloc(1, sizeof(apriltag_family_t));
    tf->name = strdup("${familyName}");
    tf->h = ${codebook.distanceAnalysis.minDistance};
    tf->ncodes = ${codebook.count};
    tf->codes = ${familyName}_codes;
    tf->width_at_border = ${widthAtBorder};
    tf->total_width = ${totalWidth};
    tf->reversed_border = 0;
    return tf;
}

static inline void ${familyName}_destroy(apriltag_family_t *tf) {
    if (!tf) return;
    free(tf->name);
    free(tf);
}

#ifdef __cplusplus
}
#endif

#endif /* _${familyName.toUpperCase()}_H */
`;
  }

  /**
   * Export C/C++ Standalone Header file.
   */
  static toCHeader(codebook: CodebookModel): string {
    const stats = codebook.entryStats;
    const arrayElements = stats
      .map((s) => `    0x${BigInt(s.bigIntValue).toString(16).toUpperCase()}ULL, /* ID ${s.id}: ${s.binaryString} */`)
      .join('\n');

    return `/* Generated by Fiducial Marker Designer */
#ifndef FIDUCIAL_CODEBOOK_${codebook.geometry.rows}X${codebook.geometry.cols}_H
#define FIDUCIAL_CODEBOOK_${codebook.geometry.rows}X${codebook.geometry.cols}_H

#include <stdint.h>

#define FIDUCIAL_GRID_ROWS ${codebook.geometry.rows}
#define FIDUCIAL_GRID_COLS ${codebook.geometry.cols}
#define FIDUCIAL_DATA_BITS ${codebook.geometry.dataBitsCount}
#define FIDUCIAL_COUNT ${codebook.count}
#define FIDUCIAL_MIN_DISTANCE ${codebook.distanceAnalysis.minDistance}
#define FIDUCIAL_MAX_ERROR_CORRECTION ${codebook.distanceAnalysis.errorCorrectionCapability}

static const uint64_t FIDUCIAL_CODES[FIDUCIAL_COUNT] = {
${arrayElements}
};

static inline int fiducial_popcount64(uint64_t x) {
#if defined(__GNUC__) || defined(__clang__)
    return __builtin_popcountll(x);
#else
    x = x - ((x >> 1) & 0x5555555555555555ULL);
    x = (x & 0x3333333333333333ULL) + ((x >> 2) & 0x3333333333333333ULL);
    x = (x + (x >> 4)) & 0x0F0F0F0F0F0F0F0FULL;
    return (int)((x * 0x0101010101010101ULL) >> 56);
#endif
}

static inline int fiducial_hamming_dist(uint64_t a, uint64_t b) {
    return fiducial_popcount64(a ^ b);
}

#endif /* FIDUCIAL_CODEBOOK_${codebook.geometry.rows}X${codebook.geometry.cols}_H */
`;
  }

  /**
   * Export to CSV format.
   */
  static toCsv(codebook: CodebookModel): string {
    const lines: string[] = ['ID,HexCode,BinaryCode,MinPairwiseDistance,MinSelfRotationDistance,BalanceRatio'];
    for (const s of codebook.entryStats) {
      lines.push(`${s.id},${s.hexString},${s.binaryString},${s.minPairwiseDistance},${s.minSelfRotationDistance},${s.balanceRatio}`);
    }
    return lines.join('\n');
  }
}
